### ISSUE TITLE
Syntax error on line 44 of /etc/apache2/apache2.conf:

### ISSUE THREAD

**Issue by hasMobi** [codemix/yii2-dockerized#1]
I am using Windows 7 and Docker Toolbox (a Linux VM running the Docker host).

After running docker-compose up I see that 2 containers are started but the web container has died immeditely. Inspecting its logs, the only error that I see is:

> 2016-03-15T20:09:45.826624531Z AH00526: Syntax error on line 44 of /etc/apache2/apache2.conf:

Using Docker version 1.10.3

**Comment by mikehaertl** [comment]
Hmm, that's weird. The `apache.conf` is located in our Yii2 base repo here: https://github.com/codemix/yii2-dockerbase/blob/master/2.0/apache/apache2.conf

Line 44 configures the document root. Did you maybe change the volumes configuration in your `docker-compose.yml`?

**Comment by hasMobi** [comment]
No. I have not done anything besides what is described as instructions in your tutorial.

**Comment by mikehaertl** [comment]
Can you check if the directory exists? You can create a temporary container like this:

```
docker-compose run --rm web bash
```

Now you should have a command line inside the container. Verify if the directory exists:

```
ls -l /var/www/html
ls -l /var/www/html/web
```

**Comment by mikehaertl** [comment]
I've just tested on Windows and everything works. Make sure, that you've installed the project somewhere below `C:\Users`. Otherwhise you can't share the volume with your container. That's a restriction of docker on windows:

https://docs.docker.com/v1.8/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume

**Comment by mikehaertl** [comment]
@hasMobi I'm closing this as there was no further feedback and I have to assume that you did not install to `C:\Users`. Feel free to add another comment if it still doesn't work.
