### ISSUE TITLE
how to set env  nginx ？

### ISSUE THREAD

**Issue by wsdo** [codemix/yii2-dockerized#12]
Is there a tutorial?

    # app:
    #     build: ./
    #     expose:
    #         - "9000"
    #     volumes:
    #         - ./:/var/www/html/
    # nginx:
    #     build: ./nginx
    #     ports:
    #         - "8080:80"
    #     links:
    #         - app
    #     volumes_from:
    #         - app

**Comment by mikehaertl** [comment]
You can check the old setup here:
https://github.com/codemix/yii2-dockerized/tree/8fa0abe9f5b42c7e5a32b4fefdeeb328fe434b42

But for now we will not include an Nginx example. The setup is easier with apache (only one container required) and there's an issue with logging from php-fpm.
