### ISSUE TITLE
First build fails

### ISSUE THREAD

**Issue by WeeSee** [codemix/yii2-dockerized#14]
The build was performed as described. When startinh the browser for the
first time, there is an error message:

```
Invalid Configuration – yii\base\InvalidConfigException
The directory is not writable by the Web process: /var/www/html/web/assets
```
Should there are some permission settings? ```chmod a+w...```

**Comment by mikehaertl** [comment]
I assume, that you map the app directory into the container in your `docker-compose.yml`. Have you seen the note on permissions in this section of the README: 

https://github.com/codemix/yii2-dockerized#31-initial-setup-of-a-development-environment

**Comment by WeeSee** [comment]
ok, thanks. i haven't read it - maybe it should be moved upper a little bit.
