### ISSUE TITLE
Running ./yii migrate/up after startup

### ISSUE THREAD

**Issue by WeeSee** [codemix/yii2-dockerized#15]
How can ```./yii migrate/up``` be executed after each container startup?

I have a Rancher running to start my conatiners and there is no user
interaction after startup where the database could be migrated manually.

**Comment by mikehaertl** [comment]
You could try a custom shell script that first runs the migration, then starts the apache. But how exactly to do this is a bit beyound the scope of this image. Just check the docker docs. There's for sure more than one way to do it.

**Comment by WeeSee** [comment]
Found an easy solution for migrations. After build, the startup script checks if a migration has to be applied and performs migration before the app launches.

In Dockerfile, add:

    # uncomment to execute migration after container startup
    RUN touch ./runtime/do_migration && chmod 777 ./runtime/do_migration

In web/index.php add:

```
// Check if migration is required
$migrateHint = __DIR__.'/../runtime/do_migration';
if (file_exists($migrateHint)) {
    exec('php '.__DIR__.'/../yii migrate/up --interactive=0',$output,$exitCode);
    if (!$exitCode || !@unlink($migrateHint)) {
        echo "migration failed\n";
        print_r($output);
        exit(1);
    }
        
}
```

Are you interested in a PR?

**Comment by mikehaertl** [comment]
I think, this is a very special demand. I don't want to include features for each and every thinkable scenario. This is only a lightweight app template that should help you get started.

But thanks anyway, glad you found a solution that works for you.
