### ISSUE TITLE
Database Exception, SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by NoorBakeer** [codemix/yii2-dockerized#17]
> PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/vendor/yiisoft/yii2/db/Connection.php:687

`'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => self::env('DB_DSN', 'mysql:host=127.0.0.1:3306;dbname=sarmad'),
            'username' => self::env('DB_USER', 'root'),
            'password' => self::env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'tablePrefix' => '',
        ],`

**Comment by mikehaertl** [comment]
Sorry, but for a bug report this is really too little information. So I will close this as it very much indicates a permission problem with you mysql container. That's not at all related to our app template here.

**Comment by giuliogatto** [comment]
I had the same error of Connection Refused, it was not a Permission problem but a problem with MySql version: for some reasons MySql 8.0 refused to connect, when changing to mysql:5.7 (in docker-compose.yml on main folder) everything just worked fine

**Comment by mikehaertl** [comment]
Hmm, is there anything to fix here? That's a general Yii / Mysql 8 issue - nothing specific to this image.

**Comment by giuliogatto** [comment]
Well, maybe momentarily force MySql to version 5.7 in docker-compose-example.yml like this:
`image: mysql:5.7`
Anyways I just wrote the comment so that anybody finding the same error will try a different version of MySql because it looks like latest is not working correctly in this case  ;)

**Comment by mikehaertl** [comment]
Makes sens. I've added a `mysql:5` constraint.
