### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by pincher2012** [codemix/yii2-dockerized#18]
Do I understand correctly that the template does not involve working with unit tests? It would be great to add tests and a description of working with them in the template. What do you think?

**Comment by mikehaertl** [comment]
Correct, no unit tests. To be honest I don't want to add anything in this regard. There are IMO too many ways how to set up unit tests and there's no right or wrong. Adding something also means, that we have to maintain the code and provide support over many years. Something I simply have no time for.

Our template is really just a very simple starting point which will need modification for every project anyway.
