### ISSUE TITLE
Invalid argument supplied for foreach() after install

### ISSUE THREAD

**Issue by giuliogatto** [codemix/yii2-dockerized#19]
Hello, everything looks fine when following your install instructions on Mac OS Mojave, including running the migrations, but when I try and check if the App is working, without any change to the code I get a:
PHP Warning – yii\base\ErrorException
Invalid argument supplied for foreach()

![screenshot 2019-02-12 at 10 31 17](https://user-images.githubusercontent.com/11378447/52629591-4ea8f080-2eba-11e9-92a3-05c0e13989f8.png)

This could be config related, but I haven't changed anything in config/web.php
What could  be causing this error?

**Comment by mikehaertl** [comment]
I'm sorry, you were hit by a typo that I just checked in yesterday. In `config/web.php` it should be `$bootstrap`. I've pushed a fix but you probably should change that manually in your setup.

**Comment by giuliogatto** [comment]
Allright! I can see that now in line 27:
`'bootstrap' => $bootsrap,` 
should be
`'bootstrap' => $bootstrap,`
Thank you for the quick answer!
