### ISSUE TITLE
The directory is not writable by the Web process: /var/www/html/web/assets

### ISSUE THREAD

**Issue by wsdo** [codemix/yii2-dockerized#4]

**Comment by mikehaertl** [comment]
What steps did you follow? And what OS do you use?

**Comment by wsdo** [comment]
ubuntu 14.04

**Comment by wsdo** [comment]
http://159.203.251.179:8080/

**Comment by wsdo** [comment]
That's just the way it starts.

**Comment by mikehaertl** [comment]
What is your `docker-compose.yml`?

**Comment by wsdo** [comment]
# For *-apache base image

web:
    build: ./
    ports:
        - "8080:80"
    expose:
        - "80"
    volumes:
        - ./:/var/www/html/
    links:
        - db
    environment:
        ENABLE_ENV_FILE: 1
        ENABLE_LOCALCONF: 1
        API_TOKEN: "c9575fee817180194a64253fd63cd4dddd0f8220"

```
# Uncomment to autostart at boottime
#restart: always

# Uncomment to send log output to syslog
#log_driver: "syslog"
#log_opt:
#    tag: "docker-web"
```

# for *-php-fpm and *-hhvm base image

#app:

# build: ./

# expose:

# \- "9000"

# volumes:

# \- ./:/var/www/html/

# links:

# \- db

# environment:

# ENABLE_ENV_FILE: 1

# ENABLE_LOCALCONF: 1

# API_TOKEN: "<YOUR GITHUB API TOKEN>"

#
#nginx:

# build: ./nginx

# ports:

# \- "8080:80"

# links:

# \- app

# volumes_from:

# \- app

db:
    image: mysql:5.6
    ports:
        - "3306:3306"
    expose:
        - "3306"

**Comment by wsdo** [comment]
almost  No changes

**Comment by mikehaertl** [comment]
Can you go to your local application directory and show the output of `ls -ln web/`? 

It should look like this:

```
$ ls -ln web/
drwxr-xr-x 96 1000 1000 4096 Apr 29 10:06 assets
drwxr-xr-x  2 1000 1000 4096 Nov 20  2014 css
-rw-r--r--  1 1000 1000  152 Mai 13 09:41 index.php
```

Note, that the files belong to user and group `1000`. Unfortunately docker has no way of configuring permissions for volumes mapped into the container.

So if you have a different owner id, you can try to fix it like this:

```
sudo chown 1000 web/assets runtime
```

**Comment by wsdo** [comment]
in container  exec   chown www-data:www-data runtime web/assets  then  success 

but  use Dockefile fail

**Comment by mikehaertl** [comment]
Ok, but that should be the same as if you use the above commands on the host. The numeric user id does not change when the volume is mapped into the container.

I think we can close this here. I'll add a note to the README.
