### ISSUE TITLE
set character-set in docker-compose?

### ISSUE THREAD

**Issue by zacksleo** [codemix/yii2-dockerized#8]
How can I set utf8 character set for the db in the docker-compose.yml file

**Comment by mikehaertl** [comment]
The DB connection already is set to `utf8`:

https://github.com/codemix/yii2-dockerized/blob/master/config/web.php#L16

If you mean, how to configure MySQL: You could map a local `mysql.cfg` file to `/etc/mysql/conf.d/` directory in your mysql container:

``` ini
[mysqld]
character-set-server=utf8
```

For details, please check the docs of the official mysql image.

**Comment by zacksleo** [comment]
Thanks!
